name: main

on: push

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup AWS Copilot
      uses: gowthamsrikrish/setup-aws-copilot@v1.3
    - run: |
        copilot --version
        aws --version
        
 
