name: main

on: push

env:
  LAUNCHABLE_TOKEN: ${{ secrets.LAUNCHABLE_TOKEN_PYTHONAPP }}
  LAUNCHABLE_DEBUG: 1
  LAUNCHABLE_REPORT_ERROR: 1
  
jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup AWS Copilot
      uses: flemzord/setup-aws-copilot@v1.3
      with:
        repo-token: ${{ secrets.PYTHONAPP }}
    - run: |
        copilot --version
        aws --version
        python -m pip install --upgrade pip
        pip3 install --user --upgrade launchable~=1.0
    - run: "launchable verify"
        
 
